spring:
  application:
    name: businessreport

  datasource:
    
    # DB
    driver-class-name: org.h2.Driver

    # スキーマ名がランダムに生成される設定をオフ
    generate-unique-name: false
    
    # ローカルdb
    url: jdbc:h2:~/reportdb
#    url: jdbc:h2:D:/02_勉強/Eclipse/bussinesreport/reportdb
    
    # インメモリ
#   url: jdbc:h2:mem:~/testdb

    username: reportuser
    password: reportuser
    
  sql:
    init:
      mode: never
      
  h2:
    console:
      enabled: true
    